// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Login(arg1:string,arg2:string):Promise<boolean>;

export function Print(arg1:string):Promise<void>;
