// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateItem(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateItem'](arg1, arg2, arg3, arg4);
}

export function DeleteItem(arg1) {
  return window['go']['main']['App']['DeleteItem'](arg1);
}

export function GetItems(arg1) {
  return window['go']['main']['App']['GetItems'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Print(arg1) {
  return window['go']['main']['App']['Print'](arg1);
}

export function UpdateItem(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateItem'](arg1, arg2, arg3, arg4, arg5);
}
