// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateItem(arg1:string,arg2:string,arg3:string,arg4:number):Promise<main.Item>;

export function DeleteItem(arg1:number):Promise<void>;

export function GetItems(arg1:string):Promise<Array<main.Item>>;

export function Login(arg1:string,arg2:string):Promise<boolean>;

export function Print(arg1:string):Promise<void>;

export function UpdateItem(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number):Promise<void>;
